### ISSUE TITLE
使用TKMybatis生成的entity 没有字段注解

### ISSUE THREAD

**Issue by whx159** [caojx-git/idea-plugin-mybatis-generator#1]
使用TKMybatis生成的entity 没有字段注解

**Comment by caojx-git** [comment]
TKMybatis 暂时只会在 主键字段上添加 javax.persistence.Id 即@Id 注解
https://github.com/caojx-git/idea-plugin-mybatis-generator/blob/master/src/main/resources/templates/entity.ftl
